/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaisieTerrainRouteImport } from './routes/saisie-terrain'
import { Route as SaisiePrixLoyerRouteImport } from './routes/saisie-prix-loyer'
import { Route as LogementsRouteImport } from './routes/logements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SaisieTerrainRoute = SaisieTerrainRouteImport.update({
  id: '/saisie-terrain',
  path: '/saisie-terrain',
  getParentRoute: () => rootRouteImport,
} as any)
const SaisiePrixLoyerRoute = SaisiePrixLoyerRouteImport.update({
  id: '/saisie-prix-loyer',
  path: '/saisie-prix-loyer',
  getParentRoute: () => rootRouteImport,
} as any)
const LogementsRoute = LogementsRouteImport.update({
  id: '/logements',
  path: '/logements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/logements': typeof LogementsRoute
  '/saisie-prix-loyer': typeof SaisiePrixLoyerRoute
  '/saisie-terrain': typeof SaisieTerrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/logements': typeof LogementsRoute
  '/saisie-prix-loyer': typeof SaisiePrixLoyerRoute
  '/saisie-terrain': typeof SaisieTerrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/logements': typeof LogementsRoute
  '/saisie-prix-loyer': typeof SaisiePrixLoyerRoute
  '/saisie-terrain': typeof SaisieTerrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/logements'
    | '/saisie-prix-loyer'
    | '/saisie-terrain'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/logements' | '/saisie-prix-loyer' | '/saisie-terrain'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/logements'
    | '/saisie-prix-loyer'
    | '/saisie-terrain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  LogementsRoute: typeof LogementsRoute
  SaisiePrixLoyerRoute: typeof SaisiePrixLoyerRoute
  SaisieTerrainRoute: typeof SaisieTerrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saisie-terrain': {
      id: '/saisie-terrain'
      path: '/saisie-terrain'
      fullPath: '/saisie-terrain'
      preLoaderRoute: typeof SaisieTerrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saisie-prix-loyer': {
      id: '/saisie-prix-loyer'
      path: '/saisie-prix-loyer'
      fullPath: '/saisie-prix-loyer'
      preLoaderRoute: typeof SaisiePrixLoyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logements': {
      id: '/logements'
      path: '/logements'
      fullPath: '/logements'
      preLoaderRoute: typeof LogementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  LogementsRoute: LogementsRoute,
  SaisiePrixLoyerRoute: SaisiePrixLoyerRoute,
  SaisieTerrainRoute: SaisieTerrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
